; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

	TITLE	D:\Réseau neuronnes - Projet Raven\Réseau\solution_lab_apprentissage_a_partir_bot\solution_lab_apprentissage_a_partir_bot\Buckland_Chapter7 to 10_Raven_apprentissage\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
